version: "3.2"
services:

  # Jaeger
  jaeger-all-in-one:
    container_name: jaeger
    command: ["--query.max-clock-skew-adjustment", "0"]
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686" # Web HTTP
      - "14268:14268" # The HTTP port for the collector service
      - "14250:14250" # The gRPC port for the collector service
    #  - "5778:5778"   # Agent config HTTP
    #  - "4317:4317"   # OTLP Receiver gRPC port
    #  - "4318:4318"   # OTLP Receiver HTTP port
    environment:
      COLLECTOR_OTLP_ENABLED: "true" # Enables/Disables OTLP Receiver

  # Zipkin
  zipkin-all-in-one:
    container_name: zipkin
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"

  # Collector
  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otel-collector-config.yaml", ""]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP http receiver
      - "55679:55679" # zpages extension
    depends_on:
      - jaeger-all-in-one
      - zipkin-all-in-one

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

networks:
  otel-inst-py-network:
