name: Quality Check

on:
  push:
    branches:
      - "*" # matches every branch
      - "*/*" # matches every branch containing a single '/'
        #      - "!ci/*" # excludes ci branches
        #      - "!master" # excludes master

jobs:
  qa:
    uses: tombenke/otel-inst-py/.github/workflows/qa.yml@master
